services:
  demo2:
      build:
        context: ./containers/demo2
        dockerfile: Dockerfile
      container_name: demo2
      ports:
        - "8188:8188"
        - "8888:8888"  # Jupyter Lab port
      volumes:
        - ./containers/demo2/output:/home/ComfyUI/output
        - ./containers/demo2/input:/home/ComfyUI/input
        - F:\WORK\Docker_Projects\ComfyUI-Containership\Windows\shared_models:/home/ComfyUI/models
        - ./containers/demo2/custom_nodes:/home/ComfyUI/custom_nodes
        - ./containers/demo2/notebooks:/notebooks
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      restart: unless-stopped
      runtime: nvidia
      command: ["/startup.sh"]
      networks:
        - comfyui_network
networks:
  comfyui_network:
    external: true
